Repository diwas7777/CodesHub, pull requests merged in 2022-10, with the labels that each got.

#3 added palindrome.ts
  typescript/palindrome.ts
Labels: hacktoberfest-accepted

#6 Create secure_password_generator.py
  Python/secure_password_generator.py
Labels: hacktoberfest-accepted, hacktoberfest

#8 Create 1's complement.py
  1's complement.py
Labels: hacktoberfest-accepted, hacktoberfest

#7 adding a c++ program for binary exponentiation
  C++/binary_exponentiation.cpp
Labels: hacktoberfest-accepted, hacktoberfest

#9 Create encrypt.py
  Python/Ransomware_Demo.py
Labels: hacktoberfest-accepted, hacktoberfest

#11 Create ransomware.py
  Python/ransomware.py
Labels: hacktoberfest-accepted, hacktoberfest

#10 Create decrypt.py
  Python/decrypt.py
Labels: hacktoberfest-accepted, hacktoberfest

#12 Added a tic-tac-toe game in python
  Python/tictactoe.py
Labels: hacktoberfest-accepted, hacktoberfest

#13 Update README.md
  README.md
Labels: hacktoberfest-accepted, hacktoberfest

#14 add color-flipper
  Javascript/color-flipper/app.js
  Javascript/color-flipper/index.html
  Javascript/color-flipper/styles.css
Labels: hacktoberfest-accepted, hacktoberfest

#16 Add bubble sort program in c
  C/bubble-sort.c
Labels: hacktoberfest-accepted, hacktoberfest

#17 GuessNumber.java
  Java/guessNumber/GuessNumber.java
Labels: hacktoberfest-accepted, hacktoberfest

#19 Add files via upload
  Java/add_two_numbers.java
Labels: hacktoberfest-accepted, hacktoberfest

#18 add binary_search.py
  Python/binary_search.py
Labels: hacktoberfest-accepted, hacktoberfest

#21 TowerOfHanoi
  C++/TowerOfHanoi.cpp
Labels: hacktoberfest-accepted, hacktoberfest

#22 Add merge sort algorithm
  Python/merge_sort.py
Labels: hacktoberfest-accepted, hacktoberfest

#25 Add files via upload
  C/palindrome.c
Labels: hacktoberfest-accepted, hacktoberfest

#23 add weaponScavenging.js
  Javascript/WeaponScavengingGame.js
Labels: hacktoberfest-accepted, hacktoberfest

#24 Added a c++ butterfly pattern file
  C++/butterfly_pattern.cpp
Labels: hacktoberfest-accepted, hacktoberfest

#29 Add magic_number.py
  Python/Magic_Number.py
Labels: hacktoberfest-accepted, hacktoberfest

#26 Added RazorPay Java coding question solution
  Java/RazorPay/MagicalBinaryString.java
  Java/RazorPay/PairMakesSum.java
Labels: hacktoberfest-accepted, hacktoberfest

#27 Create IncomeTax.java
  Java/IncomeTax.java
Labels: hacktoberfest-accepted, hacktoberfest

#30 Number palindrome
  Python/Number_Palindrome.py
Labels: hacktoberfest-accepted, hacktoberfest

#31 String Palindrome Added
  Python/String_Palindrome.py
Labels: hacktoberfest-accepted, hacktoberfest

#32 Calendar in python terminal
  calendar.py
Labels: hacktoberfest-accepted, hacktoberfest

#33 Added a telephone directory using python
  Python/Telephonedirectory.py
Labels: hacktoberfest-accepted, hacktoberfest

#35 Checks if the string is valid anagram or not
  Python/Valid Anagram.py
Labels: hacktoberfest-accepted, hacktoberfest

#34 Create validation_password_creation_solution.py
  Python/validation_password_creation_solution.py
Labels: hacktoberfest-accepted, hacktoberfest

#28 Simple calculator using java
  Java/Calculator.java
Labels: hacktoberfest-accepted, hacktoberfest

#38 Create addTwoNumber.js
  Javascript/addTwoNumber.js
Labels: hacktoberfest-accepted, hacktoberfest

#39 Fixing Hollow square pattern
  Javascript/Hollow Square Pattern.js
Labels: hacktoberfest-accepted, hacktoberfest

#41 Updated README.md and created fibonacciSequence.py
  Python/fibonacciSequence.py
  README.md
Labels: hacktoberfest-accepted, hacktoberfest

#42 added number guessing game made with python
  Python/number_guessing_game.py
Labels: hacktoberfest-accepted, hacktoberfest

#40 Create pyramidstartpattern.js
  Javascript/pyramidstartpattern.js
Labels: hacktoberfest-accepted, hacktoberfest

#46 Create Add_binary_num.cpp
  C++/Add_binary_num.cpp
Labels: hacktoberfest-accepted, hacktoberfest

#45 Create right_view_of_a_binary tree.cpp
  C++/right_view_of_a_binary tree.cpp
Labels: needFix

#48 Create bubbleSort.go
  Go/bubbleSort.go
Labels: hacktoberfest-accepted, hacktoberfest

#50 Butterfly Pattern Python Code
  Python/butterfly_pattern.py
Labels: hacktoberfest-accepted, hacktoberfest

#53 feat: Random password API
  Javascript/fastify/.gitignore
  Javascript/fastify/index.js
  Javascript/fastify/package.json
  Javascript/fastify/pnpm-lock.yaml
Labels: hacktoberfest-accepted, hacktoberfest

#54 Update function.js
  Javascript/function.js
Labels: hacktoberfest-accepted, hacktoberfest

#56 Create sum_of_n_natural_numbers.py
  Python/sum_of_n_natural_numbers.py
Labels: hacktoberfest-accepted, hacktoberfest

#59 :sparkles: added fast food cli
  C/fastFoodCLI.c
Labels: hacktoberfest-accepted, hacktoberfest

#62 Added a area of rectangle file to python
  Python/areaOfRectangle.py
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#61 Create Queue_using_linked_list
  C++/Queue_using_linked_list.cpp
Labels: hacktoberfest-accepted, hacktoberfest

#64 Added Regression model
  Python/regression_model/data.csv
  Python/regression_model/reg.py
Labels: hacktoberfest-accepted, hacktoberfest

#66 :sparkles: added python-nmap-port-scanner.py
  Python/python-nmap-port-scanner.py
Labels: hacktoberfest-accepted, hacktoberfest

#67 Add files via upload
  Java/fibonacci.java
Labels: hacktoberfest-accepted, hacktoberfest

#68 Add files via upload
  C++/palindrome_recursion.cpp
Labels: hacktoberfest-accepted, hacktoberfest

#69 add: linear search
  Python/linear_search.py
Labels: hacktoberfest-accepted, hacktoberfest

#70 add: reverse string
  Python/rev_string.py
Labels: hacktoberfest-accepted, hacktoberfest

#73 🦀 Added binary_search.rs
  Rust/binary_search.rs
  Rust/hello_world.rs
Labels: hacktoberfest-accepted, hacktoberfest

#75 Create sjf.cpp
  C++/OS/sjf.cpp
Labels: hacktoberfest-accepted, hacktoberfest

#77 Added binomial expansion series
  Python/binomial_expansion_series.py
Labels: hacktoberfest-accepted, hacktoberfest

#78 Added code for recursive factorial in python
  Python/recursive_factorial.py
Labels: hacktoberfest-accepted, hacktoberfest

#79 Added check_prime in Python
  Python/check_prime.py
Labels: hacktoberfest-accepted, hacktoberfest

#82 🦀 Added cli rock paper scissors
  Rust/rock_paper_scissors/Cargo.toml
  Rust/rock_paper_scissors/src/main.rs
Labels: hacktoberfest-accepted, hacktoberfest

#83 🦀 Created an interpreter to convert brainfuck code to text!
  Rust/brainfuck_interpreter.rs
Labels: hacktoberfest-accepted, hacktoberfest

#87 :sparkle: Added Contact Management System
  C/Contact-Managment-System.c
Labels: hacktoberfest-accepted, hacktoberfest

#88 Create katakana2hiragana
  Python/katakana2hiragana.py
Labels: hacktoberfest-accepted, hacktoberfest

#91 Create roadCrossing Game.py
  Python/roadCrossing Game.py
Labels: hacktoberfest-accepted, hacktoberfest

#93 This is a Hang Man Game
  Python/HangMan.py
Labels: hacktoberfest-accepted, hacktoberfest

#94 Update the generation function.
  Python/password_generator.py
Labels: hacktoberfest-accepted, hacktoberfest

#95 Create mad-libs-gen.py
  Python/mad-libs-gen.py
Labels: hacktoberfest-accepted, hacktoberfest

#99 Internet speed test
  Python/internetspeedtest.py
Labels: hacktoberfest-accepted, hacktoberfest

#100 pascal's triangle
  Java/PascalsTriangle.java
Labels: hacktoberfest-accepted, hacktoberfest

#101 Create ReverseStringWordWise.java
  Java/ReverseStringWordWise.java
Labels: hacktoberfest-accepted, hacktoberfest

#103 Rock Paper Scissor using random function in python
  Python/RockPaperScissor.py
Labels: hacktoberfest-accepted, hacktoberfest

#104 Digital Clock GUI
  Python/Digital_clock.py
Labels: hacktoberfest-accepted, hacktoberfest

#105 Create PalindromeTest.java
  Java/PalindromeTest.java
Labels: hacktoberfest-accepted, hacktoberfest

#106 Counting sort implementation in c++
  C++/Counting_sort.cpp
Labels: hacktoberfest-accepted, hacktoberfest

#108 Create sudoku_ManiL-Keo.py
  Python/sudoku_ManiL-Keo.py
Labels: hacktoberfest-accepted, hacktoberfest

#110 linear_search.go
  Go/linearsearch.go
Labels: hacktoberfest-accepted, hacktoberfest

#113 Added Decimal To Binary Program
  C++/DecToBinRecursive.cpp
Labels: hacktoberfest-accepted, hacktoberfest

#116 Created areaoftriangle.py
  Python/areaoftriangle.py
Labels: hacktoberfest-accepted, hacktoberfest

#119 Radix sort methodology for beginners in c++
  C++/Radix_sort.c++
Labels: hacktoberfest-accepted, hacktoberfest

#120 heap_sort added
  Python/heap_sort.py
Labels: hacktoberfest-accepted, hacktoberfest

#121 Create additon.c
  C/additon.c
Labels: hacktoberfest-accepted, hacktoberfest

#123 :sparkles: Added firstandlastoccurence.cpp
  C++/firstandlastoccurence.cpp
Labels: hacktoberfest-accepted, hacktoberfest

#125 rotate_array.cpp
  C++/rotate_array.cpp
Labels: hacktoberfest-accepted, hacktoberfest

#126 pangram_check.cpp
  C++/pangram_check.cpp
Labels: hacktoberfest-accepted, hacktoberfest

#127 reverse_array.cpp
  Java/reverse_array.cpp
Labels: hacktoberfest-accepted, hacktoberfest

#128 median_of_two_sorted_array.java
  Java/median_of_two_sorted_array.java
Labels: hacktoberfest-accepted, hacktoberfest

#129 Added algorithm to find single number in array of doubles same numbers
  Java/findSingleInArrayOfDoubles.java
Labels: hacktoberfest-accepted, hacktoberfest

#130 top_view_of_a_binary_tree.cpp
  C++/top_view_of_a_binary_tree.cpp
Labels: hacktoberfest-accepted, hacktoberfest

#131 sum_of_nodes_in_top_view_of_a_binary_tree.cpp
  C++/sum_of_nodes_in_top_view_of_a_binary_tree.cpp
Labels: hacktoberfest-accepted, hacktoberfest

#132 intersection_point_of_two_Linked_Lists.java
  Java/intersection_point_of_two_Linked_Lists.java
Labels: hacktoberfest-accepted, hacktoberfest

#134 QuickSort_on_Singly_Linked_List.java
  Java/QuickSort_on_Singly_Linked_List.java
Labels: hacktoberfest-accepted, hacktoberfest

#135 Count_divisible_pairs_in_an_array.cpp
  C++/Count_divisible_pairs_in_an_array.cpp
Labels: hacktoberfest-accepted, hacktoberfest

#136 binomial_heap.cpp
  C++/binomial_heap.cpp
Labels: hacktoberfest-accepted, hacktoberfest

#137 level_order.cpp
  C++/level_order.cpp
Labels: hacktoberfest-accepted, hacktoberfest

#138 double_hashing.cpp
  C++/double_hashing.cpp
Labels: hacktoberfest-accepted, hacktoberfest

#139 avl_tree.cpp
  C++/avl_tree.cpp
Labels: hacktoberfest-accepted, hacktoberfest

#140 expression_tree.cpp
  C++/expression_tree.cpp
Labels: hacktoberfest-accepted, hacktoberfest

#141 stepping_number.java
  Java/stepping_number.cpp
Labels: hacktoberfest-accepted, hacktoberfest

#142 reverse_doubly_linkedlist.java
  Java/reverse_doubly_linkedlist.java
Labels: hacktoberfest-accepted, hacktoberfest

#143 add
  C++/sudoku_solver.cpp
Labels: hacktoberfest-accepted, hacktoberfest

#145 Added Leap Year program in Java
  Java/LeapYear.java
Labels: hacktoberfest-accepted, hacktoberfest

#146 Create onClick.html
  Html/onClick.html
Labels: hacktoberfest-accepted, hacktoberfest

#149 Create autoChangeColor.html
  Html/autoChangeColor.html
Labels: hacktoberfest-accepted, hacktoberfest

#150 Kadanes theorem using cpp sub arrays printing. Please merge and add hacktoberfest label in it.
  C++/KDTheorem_subarrays.cpp
Labels: hacktoberfest-accepted, hacktoberfest

#151 adding temperature_converter.py
  Python/temperature_converter.py
Labels: hacktoberfest-accepted, hacktoberfest

#152 Create startPyramid.cpp
  C++/startPyramid.cpp
Labels: hacktoberfest-accepted, hacktoberfest

#153 Create hash.cs
  C#/hash.cs
Labels: hacktoberfest-accepted, hacktoberfest

#156 make calculator js
  Javascript/Calculator/index.html
  Javascript/Calculator/scripts.js
  Javascript/Calculator/storage.html
  Javascript/Calculator/storage.js
  Javascript/Calculator/style.css
Labels: hacktoberfest-accepted, hacktoberfest

#158 nth_node.cpp
  C++/nth_node.cpp
Labels: hacktoberfest-accepted, hacktoberfest

#157 count_nodes_in_circular_linkedlist.cpp
  C++/count_nodes_in_circular_linkedlist.cpp
Labels: hacktoberfest-accepted, hacktoberfest

#159 swap_nodes.cpp
  C++/swap_nodes.cpp
Labels: hacktoberfest-accepted, hacktoberfest

#160 count_word.cpp
  Java/count_word.cpp
Labels: hacktoberfest-accepted, hacktoberfest

#161 check_array.cpp
  C++/check_array.cpp
Labels: hacktoberfest-accepted, hacktoberfest

#163 binarytree_fold.py
  Python/binarytree_fold.py
Labels: hacktoberfest-accepted, hacktoberfest

#164 graph_dial.cpp
  C++/graph_dial.cpp
Labels: hacktoberfest-accepted, hacktoberfest

#165 bst_to_minheap.js
  Javascript/bst_to_minheap.js
Labels: hacktoberfest-accepted, hacktoberfest

#166 merge_two_bst.js
  Javascript/merge_two_bst.js
Labels: hacktoberfest-accepted, hacktoberfest

#169 Create functions.py
  Python/LMS/functions.py
Labels: hacktoberfest-accepted, hacktoberfest

#170 Add files via upload
  Java/exchangeValues/Main.java
Labels: hacktoberfest-accepted, hacktoberfest

#171 ping pong game
  ping pong game.py
Labels: hacktoberfest-accepted, hacktoberfest

#172 Andrew Algorithm Convex Hull
  C++/andrew_algorithm_convex_hull.cpp
Labels: hacktoberfest-accepted, hacktoberfest

#174 switchCase
  Java/switchCase/Main.java
Labels: hacktoberfest-accepted, hacktoberfest

#175 added Count Sort Algorithm
  Python/Count_Sort.py
Labels: hacktoberfest-accepted, hacktoberfest

#176 Add files via upload
  Python/exchangeValuesPython/Main.py
Labels: hacktoberfest-accepted, hacktoberfest

#177 Add files via upload
  Java/arrayList/Fruites.java
Labels: hacktoberfest-accepted, hacktoberfest

#178 Create fast_fourier_transform.cpp
  C++/fast_fourier_transform.cpp
Labels: hacktoberfest-accepted, hacktoberfest

#179 Garner's Implementation
  C++/ChineseRemainderTheorem.cpp
Labels: hacktoberfest-accepted, hacktoberfest

#180 Create index.html
  Html/fun project/index.html
Labels: hacktoberfest-accepted, hacktoberfest

#181 Create style.css
  Html/fun project/style.css
Labels: hacktoberfest-accepted, hacktoberfest

#182 Create palindrome.js
  Javascript/palindrome.js
Labels: hacktoberfest-accepted, hacktoberfest

#183 Floyds Warshall Algo Cpp implementation(Please merge and add hacktoberfest label).
  C++/Floyds_Warshell_Algo.cpp
Labels: hacktoberfest-accepted, hacktoberfest

#184 Added functionality to test password strength.
  Python/password_generator.py
Labels: hacktoberfest-accepted, hacktoberfest

#185 sum of first n squared numbers
  Python/sum_of_first_n2_natural_numbers.py
Labels: hacktoberfest-accepted, hacktoberfest

#187 Prime Factors of a number
  C++/Prime Factors of a number.cpp
Labels: hacktoberfest-accepted, hacktoberfest

#189 Added Spirograph code
  Python/spirograph.py
Labels: hacktoberfest-accepted, hacktoberfest

#190 Add files via upload
  Java/simpleInterest/Si.java
Labels: hacktoberfest-accepted, hacktoberfest

#191 0-1 Knapsack
  C++/0-1_Knapsack.cpp
Labels: hacktoberfest-accepted, hacktoberfest

#193 Tower of Hanoi using Python
  Python/Tower_of_Hanoi.py
Labels: hacktoberfest-accepted, hacktoberfest

#194 Create Monte_hall.py
  Python/Monte_hall.py
Labels: hacktoberfest-accepted, hacktoberfest

#195 Identical Trees in c
  C/Tree traverals/IdenticalTrees.c
Labels: hacktoberfest-accepted, hacktoberfest

#196 Create functionMathsAll.html
  Html/Class 12th Solutions/functionMathsAll.html
Labels: hacktoberfest-accepted, hacktoberfest

#198 Knight Tour Problem In Java
  Java/KnightTourProblem.java
Labels: hacktoberfest-accepted, hacktoberfest

#199 screenshot.py
  Python/screenshot.py
Labels: hacktoberfest-accepted, hacktoberfest

#200 recon.py
  Python/recon.py
Labels: hacktoberfest-accepted, hacktoberfest

#205 feat: Add a custom theme for CodesHub website
  _config.yml
Labels: hacktoberfest-accepted, hacktoberfest

#206 The code maximizes the number S
  Python/Python/maximize.py
Labels: hacktoberfest-accepted, hacktoberfest

#208 subdomain.py
  Python/subdomain.py
Labels: hacktoberfest-accepted, hacktoberfest

#209 hashcracker.py
  Python/hashcracker.py
Labels: hacktoberfest-accepted, hacktoberfest

#207 mnap.py
  mnap.py
Labels: hacktoberfest-accepted, hacktoberfest

#210 Create nmap.py
  Python/nmap.py
Labels: hacktoberfest-accepted, hacktoberfest

#211 Added codes of hashmap and hashset
  C++/Design_HashMap.cpp
  C++/Design_HashSet.cpp
Labels: hacktoberfest-accepted, hacktoberfest

#212 Add TemperatureConverter.cpp
  C++/TemperatureConverter.cpp
Labels: hacktoberfest-accepted, hacktoberfest

#214 Create generate-random-color.cpp
  C++/generate-random-color.cpp
Labels: hacktoberfest-accepted, hacktoberfest

#215 Merge sort java
  Java/merge_sort.java
Labels: hacktoberfest-accepted, hacktoberfest
